export const randomSongs = [
    "Bohemian Rhapsody",
    "Stairway to Heaven",
    "Hotel California",
    "Imagine",
    "Hey Jude",
    "Smells Like Teen Spirit",
    "Sweet Child O' Mine",
    "Billie Jean",
    "Wonderwall",
    "Like a Rolling Stone",
    "What a Wonderful World",
    "Purple Haze",
    "Let It Be",
    "Yesterday",
    "Paint It Black",
    "Lose Yourself",
    "Hallelujah",
    "Uptown Funk",
    "All of Me",
    "Rolling in the Deep",
    "Someone Like You",
    "Shape of You",
    "Thinking Out Loud",
    "Perfect",
    "Old Town Road",
    "Blinding Lights",
    "Dance Monkey",
    "Shallow",
    "Sunflower",
    "God's Plan",
    "Bad Guy",
    "Senorita",
    "Rockstar",
    "One Dance",
    "Sicko Mode",
    "Lucid Dreams",
    "Bohemian Like You",
    "Mr. Brightside",
    "Counting Stars",
    "Royals",
    "Just the Way You Are",
    "Sorry",
    "Hello",
    "Can't Feel My Face",
    "Lean On",
    "Closer",
    "Despacito",
    "7 Rings",
    "Truth Hurts",
    "Thank U, Next"
  ];
  